
name: flutter App build

on:
  push:
    branches: 
      - main

jobs:
  build_android:
    name: android app
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: "11"
    
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
      - run: flutter --version

      - name: installing dependencies
        run: flutter pub get
      
      - name: prepare for android build
        run: flutter build apk
            
      - name: release apk
        uses: actions/upload-artifact@v3
        with:
          name: apk-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macOS-latest
    name: ios app
    needs: [build_android]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: "11"
    
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
      - run: flutter --version

      - name: installing dependencies
        run: flutter pub get
      
      - name: check ipk option
        run: flutter build ipa -h

      - name: prepare for android build
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphones
          mkdir Payload
          cd Payload
          ln - ../Runner.app
          cd ..
          zip -r app.ipa Payload
          
      - name: release app
        uses: actions/upload-artifact@v3
        with:
          name: ios-${{ github.run_number }}
          path: build/ios/iphoneos/app.ipa
